name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v4
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/bone-age-estimation:latest # Replace with your Docker Hub username/repo
        # Optional: Add tags for specific versions or branches
        # tags: |
        #   ${{ secrets.DOCKERHUB_USERNAME }}/bone-age-estimation:latest
        #   ${{ secrets.DOCKERHUB_USERNAME }}/bone-age-estimation:${{ github.sha }}

    # Optional: Add a step to deploy to a cloud provider or server
    # - name: Deploy to server
    #   uses: appleboy/ssh-action@master
    #   with:
    #     host: ${{ secrets.SERVER_HOST }}
    #     username: ${{ secrets.SERVER_USERNAME }}
    #     key: ${{ secrets.SSH_PRIVATE_KEY }}
    #     script: |
    #       docker pull ${{ secrets.DOCKERHUB_USERNAME }}/bone-age-estimation:latest
    #       docker stop bone-age-app || true
    #       docker rm bone-age-app || true
    #       docker run -d --name bone-age-app -p 7860:7860 ${{ secrets.DOCKERHUB_USERNAME }}/bone-age-estimation:latest
